package hr.dtakac.prognoza.ui.theme.fair

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF7E5700)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDEAC)
val md_theme_light_onPrimaryContainer = Color(0xFF281900)
val md_theme_light_secondary = Color(0xFF6E5C40)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF8DFBB)
val md_theme_light_onSecondaryContainer = Color(0xFF261904)
val md_theme_light_tertiary = Color(0xFF4E6542)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD1EABF)
val md_theme_light_onTertiaryContainer = Color(0xFF0D2005)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1B16)
val md_theme_light_surfaceVariant = Color(0xFFEFE0CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4E4539)
val md_theme_light_outline = Color(0xFF807567)
val md_theme_light_inverseOnSurface = Color(0xFFF8EFE7)
val md_theme_light_inverseSurface = Color(0xFF34302A)
val md_theme_light_inversePrimary = Color(0xFFFFBA38)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF7E5700)

val md_theme_dark_primary = Color(0xFFFFBA38)
val md_theme_dark_onPrimary = Color(0xFF432C00)
val md_theme_dark_primaryContainer = Color(0xFF604100)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDEAC)
val md_theme_dark_secondary = Color(0xFFDBC3A1)
val md_theme_dark_onSecondary = Color(0xFF3D2E16)
val md_theme_dark_secondaryContainer = Color(0xFF55442A)
val md_theme_dark_onSecondaryContainer = Color(0xFFF8DFBB)
val md_theme_dark_tertiary = Color(0xFFB5CEA4)
val md_theme_dark_onTertiary = Color(0xFF213618)
val md_theme_dark_tertiaryContainer = Color(0xFF374C2C)
val md_theme_dark_onTertiaryContainer = Color(0xFFD1EABF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1B16)
val md_theme_dark_onBackground = Color(0xFFEAE1D9)
val md_theme_dark_surface = Color(0xFF1F1B16)
val md_theme_dark_onSurface = Color(0xFFEAE1D9)
val md_theme_dark_surfaceVariant = Color(0xFF4E4539)
val md_theme_dark_onSurfaceVariant = Color(0xFFD2C4B4)
val md_theme_dark_outline = Color(0xFF9B8F80)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
val md_theme_dark_inverseSurface = Color(0xFFEAE1D9)
val md_theme_dark_inversePrimary = Color(0xFF7E5700)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFBA38)


val seed = Color(0xFFFFB300)
