#!/usr/bin/env bash

ldpi='30';
mdpi='40';
hdpi='60';
xhdpi='80';
xxhdpi='120';
xxxhdpi='160';
output_path="../../androidApp/src/main/res"

echo "Converting dark SVGs to Android drawables..."
cd dark
for file in *.svg
do
    output_file="dark_${file%.*}.png";
    echo "  $output_file"
    inkscape -w $ldpi -h $ldpi $file -o $output_path/drawable-ldpi/$output_file;
    inkscape -w $mdpi -h $mdpi $file -o $output_path/drawable-mdpi/$output_file;
    inkscape -w $hdpi -h $hdpi $file -o $output_path/drawable-hdpi/$output_file;
    inkscape -w $xhdpi -h $xhdpi $file -o $output_path/drawable-xhdpi/$output_file;
    inkscape -w $xxhdpi -h $xxhdpi $file -o $output_path/drawable-xxhdpi/$output_file;
    inkscape -w $xxxhdpi -h $xxxhdpi $file -o $output_path/drawable-xxxhdpi/$output_file;
done;

echo && echo "Converting light SVGs to Android drawables..."
cd ../light
for file in *.svg
do
    output_file="light_${file%.*}.png";
    echo "  $output_file"
    inkscape -w $ldpi -h $ldpi $file -o $output_path/drawable-ldpi/$output_file;
    inkscape -w $mdpi -h $mdpi $file -o $output_path/drawable-mdpi/$output_file;
    inkscape -w $hdpi -h $hdpi $file -o $output_path/drawable-hdpi/$output_file;
    inkscape -w $xhdpi -h $xhdpi $file -o $output_path/drawable-xhdpi/$output_file;
    inkscape -w $xxhdpi -h $xxhdpi $file -o $output_path/drawable-xxhdpi/$output_file;
    inkscape -w $xxxhdpi -h $xxxhdpi $file -o $output_path/drawable-xxxhdpi/$output_file;
done;

echo && echo "Done!"
