package hr.dtakac.prognoza

const val OSM_NOMINATIM_BASE_URL = "https://nominatim.openstreetmap.org/"

const val ACTION_APP_WIDGET_CURRENT_CONDITIONS_UPDATE = "hr.dtakac.prognoza.ACTION_CURRENT_CONDITIONS_UPDATE"
const val REQUEST_CODE_APP_WIDGET_CURRENT_CONDITIONS_UPDATE = 2
const val REQUEST_CODE_APP_WIDGET_CURRENT_CONDITIONS_INTENT_TRAMPOLINE = 1