#!/usr/bin/env bash

mdpi='100';
ldpi='75';
hdpi='150';
xhdpi='200';
xxhdpi='300';
xxxhdpi='400';

for file in *
do
    filename="${file%.*}";
    inkscape -w $ldpi -h $ldpi $file -o drawable-ldpi/$filename.png;
    inkscape -w $mdpi -h $mdpi $file -o drawable-mdpi/$filename.png;
    inkscape -w $hdpi -h $hdpi $file -o drawable-hdpi/$filename.png;
    inkscape -w $xhdpi -h $xhdpi $file -o drawable-xhdpi/$filename.png;
    inkscape -w $xxhdpi -h $xxhdpi $file -o drawable-xxhdpi/$filename.png;
    inkscape -w $xxxhdpi -h $xxxhdpi $file -o drawable-xxxhdpi/$filename.png;
done;